#!/usr/bin/env node
/**
 * generate-qr.mjs — build-time QR SVG generator (DATA-06).
 *
 * Reads the single swap-point config `src/lib/config/sites.js` (two PLACEHOLDER
 * absolute external URLs) and, for each site, renders a crisp inline SVG QR code
 * via the `qrcode` lib. Emits an importable module `src/lib/data/qr.generated.js`
 * exporting `qrCodes = [{ id, label, url, svg }]` — SVG strings inlined into the
 * bundle (no static/ asset, no runtime fetch, prerender-safe).
 *
 * Pitfall 5 guard: each QR encodes the ABSOLUTE external destination. A relative
 * or base-prefixed (`/Eman_dashboard/…`) target is a BUILD FAILURE — the tool
 * asserts `url.startsWith('http')` and never routes a target through the app base.
 *
 * Exits 1 on any bad URL; 0 when both codes emit.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';
import { sites } from '../src/lib/config/sites.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'lib', 'data', 'qr.generated.js');

let failed = false;
const check = (ok, label) => {
	console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}`);
	if (!ok) failed = true;
};

console.log('generate-qr: rendering inline-SVG QR codes for the configured sites\n');

const qrCodes = [];
for (const site of sites) {
	const { id, label, url } = site;
	// Absolute-URL guard (Pitfall 5): a base-prefixed / relative target is a build failure.
	check(
		typeof url === 'string' && url.startsWith('http'),
		`site "${id}" url is absolute (startsWith http): ${url}`
	);
	// Belt-and-suspenders: the app base must never leak into a QR target.
	check(!String(url).includes('/Eman_dashboard/'), `site "${id}" url is not base-prefixed`);
	if (failed) break;

	const svg = await QRCode.toString(url, { type: 'svg', margin: 1, errorCorrectionLevel: 'M' });
	qrCodes.push({ id, label, url, svg });
}

if (failed) {
	console.log('\ngenerate-qr: FAILED — fix src/lib/config/sites.js (absolute https:// URLs only)');
	process.exit(1);
}

const banner =
	'// AUTO-GENERATED by tools/generate-qr.mjs — DO NOT EDIT.\n' +
	'// Source of truth: src/lib/config/sites.js. Re-run `node tools/generate-qr.mjs` to regenerate.\n' +
	'// Inline-SVG QR codes for the two configured external site URLs (no runtime fetch).\n';

const body = `export const qrCodes = ${JSON.stringify(qrCodes, null, 2)};\n`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, banner + body, 'utf8');

console.log('\ngenerate-qr: emitted src/lib/data/qr.generated.js');
for (const { id, url } of qrCodes) console.log(`  • ${id} → ${url}`);
console.log('\ngenerate-qr: PASSED');
process.exit(0);
